### ISSUE TITLE
Address lookup timeout value should be driven by ENV var

### ISSUE THREAD

**Issue by woodpigeon** [EnvironmentAgency/flood-risk-engine#150]
The baseline requirement here is that an ENV var _must_ drive the addresslookup timeout - we want to avoid a code release  in order to configure this release. So I suppose it make sense for the host app in an initializer to read the ENV var and set it as a config setting on the engine. It is then used when making address loookups. Alternatively the engine could look for the ENV var?

**Comment by autotelik** [comment]
Isn't this how it already is ? I set it up so in FO sets this in secrets

  address_facade_timeout:  <%= ENV['ADDRESS_FACADE_TIMEOUT'] || '10' %>

IN Engine uses the secret

**Comment by woodpigeon** [comment]
I should have checked first, sorry. Are you happy the engine makes an assumption about what's in the host app's Rails.secrets? Feels like a smell. Looks like we do it for airbrake config too. I don't have a suggestion for improving this. Adding a duplicate set of configuration settings in the engine's config (so the main app can confiigure them directly on the engine) feels a bit OTT.

**Comment by woodpigeon** [comment]
Done
