### ISSUE TITLE
Back button - Form resubmission problems

### ISSUE THREAD

**Issue by autotelik** [EnvironmentAgency/flood-risk-engine#38]
Scenario :

Visit : http://localhost:3000/fre/enrollments/24/steps/check_location

After I choose Nothing, get expected  `Please select yes or no` Error
Then I subsequently choose No - am redirected to static page
When I use the Back Button
Then I should return to this check_location page

But I get 

**Confirm Form Resubmission
ERR_CACHE_MISS**

We had this issue in WEX and solved it with back button cache busters and when a form involved
by using this technique - https://en.wikipedia.org/wiki/Post/Redirect/Get   - basically intercepting the post and redirecting to a Get

I have tried adding back button cache buster to the static page controller
I have tried  making the redirect url more specific to force a GET i.e

 In app/forms/flood_risk_engine/steps/check_location_form.rb
`form.redirection_url = Rails.application.routes.url_helpers.page_path(:contact_ea_location)`

No joy .. I'm not sure where else in the new Step/Enrollment/Form world to try  the Post/Redirect/Get

**Comment by autotelik** [comment]
code changes for the above:

https://github.com/EnvironmentAgency/flood-risk-engine/pull/39/files

**Comment by reggieb** [comment]
I'll have a look in the morning.

**Comment by autotelik** [comment]
for background .. I think above the redirect is occuring too late in the chain,  its the original call to Stpes#update that needs redirecting .. I think in wex we had a hook before update where we could intercept these edge cases, and stop them going to the update method as a PATCH/POST at all - and instead redirected them to a specific GET method.

this was required around address processing with the postcode lookup

not sure given the current flux in pages (rumour that this page may go all together anyway) whether worth spending too much/any time on this now  - but something we'll have to keep an eye on and remember to test how the back button works after each form submission

**Comment by reggieb** [comment]
You can get the app to work without getting a "Confirm Form Resubmission" by changing the step controller from

```
      def update
        enrollment.go_forward
        success = save_form!
        if form.redirect?
          redirect_to(form.redirection_url)
        elsif success
          redirect_to step_url
        else
          render :show, locals: locals
        end
      end
```

to

```
      def update
        enrollment.go_forward
        success = save_form!
        if form.redirect?
          redirect_to(form.redirection_url)
        elsif success
          redirect_to step_url
        else
          step_back
          redirect_to step_url
        end
      end
```

But then you lose the error message on the failed form submission.

Is the current behaviour actually a problem? It is an edge case, and if you confirm you are happy with the form being resubmitted, you get to the right place. The behaviour is the correct behaviour - the action you are being taken back to is a form submission via PUT.

**Comment by autotelik** [comment]
I'm not the QA guy but AFAIK its a problem. Tim Stone raised it as a QA point and certainly in wex we had to make sure every page went back smoothly to the previous page to pass QA 

I think we'll get these current stories passed now on understanding we fix later -  I suspect it wont be an edge case once we get to addresses

**Comment by reggieb** [comment]
There is a strategy here that might work: https://github.com/tommeier/rails-prg

That gem looks broken, but it shouldn't be too difficult to replicate the same behaviour.

It looks to be passing the submitted form data back to the edit action (via redirect) on error.

**Comment by autotelik** [comment]
yeah looks like they understand the problem very well .. it was pretty easy to roll our own, looks similar with a before update hook

**Comment by reggieb** [comment]
I've just submitted a fix that works. @autotelik can you have a look and see what you think

**Comment by reggieb** [comment]
The "fix" has been merged with develop. I presume this issue can be closed after this is tested.
