### ISSUE TITLE
Consolidate steps locale files into one location

### ISSUE THREAD

**Issue by woodpigeon** [EnvironmentAgency/flood-risk-engine#61]
I think all step local files are best placed (most logically) under `config/locales/flood_risk_engine/enrollments/steps` - however some are currently under `flood_risk_engine/` and some under `..steps/show` so there is a small task required to re-group them.

**Comment by autotelik** [comment]
:+1:  for  `enrollments/steps`

**Comment by woodpigeon** [comment]
Done
