### ISSUE TITLE
Make StepsController raise errors if there is an issue moving a step forward or back

### ISSUE THREAD

**Issue by reggieb** [EnvironmentAgency/flood-risk-engine#62]
Currently the controller methods `step_forward` and `step_back` both fail silently, making it difficult to diagnose problems.

It should just require changing the `enrollment.go_forward` and `enrollment.go_back` calls to the bang alternatives `enrollment.go_forward!` and `enrollment.go_back!` but that needs to be tested, and tests added to ensure the behaviour is preserved. Also need to ensure a tidy way of recovering from the error is in place.

**Comment by woodpigeon** [comment]
Is this still an issue @reggieb? Not suggesting we fix right now, just doing some housekeeping!

**Comment by reggieb** [comment]
If it was - I think we'd have heard about it. Lets drop it.
