### ISSUE TITLE
Runtime errors during the loading of a form object get discarded

### ISSUE THREAD

**Issue by woodpigeon** [EnvironmentAgency/flood-risk-engine#67]
If there is a runtime error in a form object, say while you are developing/debugging the form, you get a 'No form object defined for step xxx' error because of the error handler in `setup_form_object` in `app/factories/flood_risk_engine/steps/form_object_factory.rb:41`

**Comment by autotelik** [comment]
I added a logger debug so you can see the actual error in the logs now 

.. Rails.logger.debug(x.inspect)

**Comment by woodpigeon** [comment]
Looks like the error handler was removed so closing this issue
