### ISSUE TITLE
validations run twice

### ISSUE THREAD

**Issue by autotelik** [EnvironmentAgency/flood-risk-engine#82]
Apart from being massively inefficient this can cause weird edge cases for example :

Address look up time outs. Error reported. Redirect occurs, and then validations are run again,
but this time address lookup does not time out.

So the page does not go forward, but no errors are displayed either

**Comment by woodpigeon** [comment]
@autotelik is this still an issue do you know?

**Comment by autotelik** [comment]
@woodpigeon Not sure, but haven't particularly noticed this one

**Comment by woodpigeon** [comment]
Closing as we no longer believe this is an issue
